name: Test latest cect

on:
  schedule:
    - cron: "1 1 1 * *"
  push:
    branches: [ master, development, experimental, ow* ]
  pull_request:
    branches: [ master, development, experimental, ow* ]

jobs:
  build:

    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        runs-on: [ubuntu-latest, macos-latest]
        python-version: [ "3.13" ]

    steps:
    - uses: actions/checkout@v7

    - name: Set up Python  ${{ matrix.python-version }}
      uses: actions/setup-python@v7
      with:
        python-version:  ${{ matrix.python-version }}

    - name: Install HDF5 for pytables on macos-latest
      if: ${{ matrix.runs-on == 'macos-latest' }}
      run: |
        brew install hdf5
        
    - name: Install OMV
      run: |
        pip install git+https://github.com/OpenSourceBrain/osb-model-validation
        
    - name: Install latest development version of cect
      run: |
        # This is where the latest cect is developed before a release is made, important to test this regularly. 
        pip install git+https://github.com/pgleeson/ConnectomeToolbox@development

        pip list

    - name: Install c302
      run: |
        pip install .
        pip list
        

    - name: Run some examples
      run: |
        cd c302
        mkdir examples
        python c302_IClamp.py A
        omv list -V
        omv install NEURON # Need to install NEURON
        which nrnivmodl
        
    - name: Run test script
      run: |
        export NEURON_HOME=$pythonLocation
        pip install ruff
        ./test.sh
        
    - name: Final version info
      run: |
        pip list
        env
        ls -lath
